### ISSUE TITLE
Criar RSS e publicar no iTunes

### ISSUE THREAD

**Issue by alanhoff** [nodebr/podcast#2]
Precisamos criar um RSS para o podcast e publicar este link no iTunes, mais instruções: https://www.apple.com/br/itunes/podcasts/specs.html

**Comment by SamuelKlein** [comment]
Falar com a galera do Hack'n'cast. http://hackncast.org
Ele já fazem publicações no Podcast já tem um bom tempo.

;)

**Comment by enieber** [comment]
conversando com o Magnun Leno do hackncast ele escreveu um plugin pro pelican...que sabe pode ajudar  https://github.com/magnunleno/pelican-podcast-feed

**Comment by jeanlucaslima** [comment]
@alanhoff você ainda está tocando o podcast? Se não, tem gente interessada lá na comunidade. :-)

**Comment by alanhoff** [comment]
@jeanleonino manda bala

**Comment by henriquesosa** [comment]
@alanhoff gostaria de falar contigo para saber onde parou. contatos e afins para darmos seguimento ao podcast.

**Comment by alanhoff** [comment]
@henriquesosa não tenho nenhum contato privado. A gravadora que gravou o podcast está na descrição desta tarefa e o pessoal que estava lá junto são membros na comunidade, nenhum mistério :-)

**Comment by enieber** [comment]
essa issue pode ser fechada?

https://itunes.apple.com/br/podcast/nodebr-cast-1/id1119698678?i=1000369834854&l=en&mt=2

**Comment by alanhoff** [comment]
Yes sir!

**Comment by aurium** [comment]
Olá pessoal! Não encontrei nenhum link de feed em https://itunes.apple.com/br/podcast/nodebr-cast-1/id1119698678?i=1000369834854&l=en&mt=2 e eu gostaria de acompanhar o podcast no meu AntennaPod. O itunes provê RSS de alguma forma?

**Comment by enieber** [comment]
não sei como funciona o itunes, mas o RSS do NodeBR Podecast é esse http://feeds.soundcloud.com/users/soundcloud:users:171687958/sounds.rss
